# Generated by Django 5.1.4 on 2025-01-16 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blogs', '0003_blogauthormodel_first_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogmodel',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='app_blogs.blogtagmodel', verbose_name='tags'),
        ),
    ]
